### ISSUE TITLE
大佬，能不能帮忙封包分享

### ISSUE THREAD

**Issue by RmileEVELYNN** [yaobiao131/downkyicore#1]
老作者没有维护，看您已经解决，但是看您的代码不怎么封装，感谢分享，谢谢

**Comment by yaobiao131** [comment]
> 老作者没有维护，看您已经解决，但是看您的代码不怎么封装，感谢分享，谢谢

晚些我打包一下

**Comment by RmileEVELYNN** [comment]
非常感谢，实在是小白，整不明白怎么弄，

**Comment by yaobiao131** [comment]
https://github.com/yaobiao131/downkyicore/releases/tag/9999.0.0

**Comment by RmileEVELYNN** [comment]
> https://github.com/yaobiao131/downkyicore/releases/tag/9999.0.0

收到，感谢
