### ISSUE TITLE
文件命名“视频发布时间”在下载合集视频中，会统一用最新视频的那个时间而不是各个视频的时间

### ISSUE THREAD

**Issue by kidzgy** [yaobiao131/downkyicore#103]
https://www.bilibili.com/video/BV1de411B7eR

以这个为例，目前该合集有114个视频，在设置文件命名选项中，将“视频发布时间”加入到文件名，解析该链接页面下的所有视频并下载，可以发现，下载的全部文件，都是以最新视频的时间为准，比如全部文件名的“视频发布时间”都是2024.05.19，很明显这是个BUG。

![20240521103009](https://github.com/yaobiao131/downkyicore/assets/6967810/991bdd26-f13c-47a2-a8cf-0898b8ac3391)

**Comment by yaobiao131** [comment]
问题已知，后续修复

**Comment by yaobiao131** [comment]
由于b站分p接口无法拿到每一个的发布时间，重新请求一次的话又比较浪费时间。故目前暂时不解决

**Comment by szbiao218** [comment]
> 由于b站分p接口无法获取每个的发布时间，重新请求一次的话又比较浪费时间。目前暂时无法解决

好像因为同样的原因，分p合集的标题也是同一个视频的标题。
