### ISSUE TITLE
当一个链接是合集时，左下角的全选打勾完全没用

### ISSUE THREAD

**Issue by 1983sxj** [yaobiao131/downkyicore#11]
当一个链接是合集时，比如这个BV1v64y1H7bG
![QQ截图20231227203315](https://github.com/yaobiao131/downkyicore/assets/104215313/ef0f51e7-4968-4429-8ec4-966ae66be2a2)
点全选完全没反应，列表内视频未被选中
![QQ截图20231227203419](https://github.com/yaobiao131/downkyicore/assets/104215313/dea9607c-e7e2-41a3-b1b5-1fa5ef661965)
这时候如果点解析，只能解析第一条视频
![QQ截图20231227203509](https://github.com/yaobiao131/downkyicore/assets/104215313/8b56badd-29ca-4e37-a509-720fbb88424a)
点击其中任意一条并用快捷键选中所有才能全选，而且取消全选也不能取消所有视频的选中
![QQ截图20231227203649](https://github.com/yaobiao131/downkyicore/assets/104215313/a1e64f1a-d04d-4d06-b361-ab66be1e0576)
![QQ截图20231227203739](https://github.com/yaobiao131/downkyicore/assets/104215313/e490bc89-7d14-48ba-bfb9-c296d54215ce)
抱歉有点啰嗦了。。。忘记说了，我设置的是视频不自动解析，只解析选中项

**Comment by yaobiao131** [comment]
全选确实是一个已知bug、后续我会修复，暂时只能用crtl+a全选，取消就比较麻烦
