### ISSUE TITLE
希望增加可以分别将文件下载到单独文件夹里的功能

### ISSUE THREAD

**Issue by MexanoCM** [yaobiao131/downkyicore#111]
希望增加可以分别将文件下载到单独文件夹里的功能，这样在批量下载视频时文件就不会很乱

![syt](https://github.com/yaobiao131/downkyicore/assets/165735745/01204d5c-140f-4264-a4f6-ed6872513ebd)

**Comment by yaobiao131** [comment]
自行设置中调整命名方式就可以实现
