### ISSUE TITLE
B站接口应该改了，有的视频下载失败了

### ISSUE THREAD

**Issue by ingale726** [yaobiao131/downkyicore#113]
24.6.3测试

**Comment by ingale726** [comment]
@yaobiao131

**Comment by ingale726** [comment]
https://www.bilibili.com/video/BV1Gm421p7DL/?spm_id_from=333.1007.tianma.1-1-1.click&vd_source=37a6b4f42a12e15700931e59f902d6fb

**Comment by yaobiao131** [comment]
测试均能下载
