### ISSUE TITLE
【bug】视频能解析，但不能下载

### ISSUE THREAD

**Issue by th10010** [yaobiao131/downkyicore#118]
下载一部系列视频，能解析但是不能下载，无论正片还是花絮，都无法下载。
链接为：
https://www.bilibili.com/bangumi/play/ss39636
![微信截图_20240621123531](https://github.com/yaobiao131/downkyicore/assets/55772277/7070f886-9d8a-4f79-9988-a3f7051ec0b3)
![微信截图_20240621123653](https://github.com/yaobiao131/downkyicore/assets/55772277/73930baa-4178-4e73-8053-312423dfae2e)

**Comment by yaobiao131** [comment]
这边测试均能下载
