### ISSUE TITLE
请问一下下载失败是什么原因？

### ISSUE THREAD

**Issue by jzfzzzz** [yaobiao131/downkyicore#119]
这个是链接：https://www.bilibili.com/bangumi/play/ep731836?spm
![Snipaste_2024-06-26_17-11-43](https://github.com/yaobiao131/downkyicore/assets/107303455/40505dbd-fdb8-40f9-9fd7-69b3acde45e8)
_id_from=333.337.0.0

下载番剧是正常的

**Comment by Norman-Jean** [comment]
![PixPin_2024-07-10_09-14-19](https://github.com/yaobiao131/downkyicore/assets/48086973/d5acb320-f502-46ca-a455-136feac7ad7f)
你是大会员吗？
