### ISSUE TITLE
mac电脑m2芯片，安装arm64的安装包，打开报错，显示app损坏

### ISSUE THREAD

**Issue by lmf-2021** [yaobiao131/downkyicore#12]
<img width="986" alt="image" src="https://github.com/yaobiao131/downkyicore/assets/88175965/55b5bdae-3468-4285-b5a3-2d8733d736a5">

**Comment by yaobiao131** [comment]
因为没有签名，暂时可以自行签名一下。下个版本我加上下签名

**Comment by yaobiao131** [comment]
m系列因为我没有，所以没有过多测试，intel的是可以开启任何来源就可以用

**Comment by lmf-2021** [comment]
作者这个自行签名是指什么呀

**Comment by yaobiao131** [comment]
> 作者这个自行签名是指什么呀

你可以尝试打开任意来源或者隐私和安全性里面看一下有没有仍然打开

**Comment by lmf-2021** [comment]
<img width="751" alt="image" src="https://github.com/yaobiao131/downkyicore/assets/88175965/5361da58-ba16-44c0-9b0b-96b431eb09f1">
还是打不开

**Comment by yaobiao131** [comment]
> <img alt="image" width="751" src="https://private-user-images.githubusercontent.com/88175965/293448380-5361da58-ba16-44c0-9b0b-96b431eb09f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MjE0MjcsIm5iZiI6MTcwMzkyMTEyNywicGF0aCI6Ii84ODE3NTk2NS8yOTM0NDgzODAtNTM2MWRhNTgtYmExNi00NGMwLTliMGItOTZiNDMxZWIwOWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDA3MjUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiN2FmMDg3MGYwYTIxYWIyMWQyMzdjNzVlMDJkNTZhN2ZmNzBkYWI2ZTNkM2U1M2ZjZWM0YzU0MjJjYzdhNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9TgVuSUNR48qwUgV7YFwE29VPDsnIMmNplzsVDCKiO0"> 还是打不开

链接: https://pan.baidu.com/s/1iwTSf70sfeJN0v_wHQptrA?pwd=2vvs 提取码: 2vvs 
--来自百度网盘超级会员v8的分享 我发一个版本。能否帮我测试下能不能打开

**Comment by lmf-2021** [comment]
作者牛逼，启动成功了

**Comment by lmf-2021** [comment]
作者我有问题想问一下，为什么现在哔哩下载姬，似乎只能下载480清晰度了，1080清晰度似乎下载不了，这是因为什么呢

**Comment by yaobiao131** [comment]
> 作者我有问题想问一下，为什么现在哔哩下载姬，似乎只能下载480清晰度了，1080清晰度似乎下载不了，这是因为什么呢

登录就可以下载高清晰度

**Comment by lmf-2021** [comment]
登录可以下载高清了，作者厉害啊
