### ISSUE TITLE
选择部分视频后，点击解析选中项，实际会解析全部视频

### ISSUE THREAD

**Issue by luceln** [yaobiao131/downkyicore#125]
1. 打开多p的视频，选中一部分需要下载的视频
2. 点击解析视频，选择解析选中项
3. 程序实际会从头开始开始解析，解析全部视频
![error](https://github.com/user-attachments/assets/86533f0d-13c5-4401-953f-dc1d104b3bf0)

**Comment by yaobiao131** [comment]
已知问题，已修复。等待新版本发布





------------------ 原始邮件 ------------------
发件人: luceln ***@***.***&gt;
发送时间: 2024年7月19日 10:01
收件人: yaobiao131/downkyicore ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaobiao131/downkyicore] 选择部分视频后，点击解析选中项，实际会解析全部视频 (Issue #125)

**Comment by fs1314** [comment]
还真是，我刚想发布这个议题（；´д｀）ゞ

**Comment by MisteryLiuCode** [comment]
这个问题还存在

**Comment by yaobiao131** [comment]
最新版本已修复
