### ISSUE TITLE
下载带有特殊标题的视频会出错

### ISSUE THREAD

**Issue by fs1314** [yaobiao131/downkyicore#129]
如图，下载av57508094这个视频之后，下载目录会出现两个文件夹。但是点进去之后都是空文件夹。
但是选中这两个文件，查看文件大小时并不为空。并且如果想要删除这两个文件夹也不行
[20240816(0).log](https://github.com/user-attachments/files/16632636/20240816.0.log)
![QQ截图20240816114012](https://github.com/user-attachments/assets/10a675c5-75f7-4f50-ad7d-33379daae896)
![QQ截图20240816113819](https://github.com/user-attachments/assets/fe449ae7-188c-47c9-b46b-709112c6795d)
![QQ截图20240816113813](https://github.com/user-attachments/assets/ba654154-142c-4773-8534-4eedc08d195e)
![QQ截图20240816113806](https://github.com/user-attachments/assets/5ec1eab3-395d-4829-869e-035aa242cc28)
![QQ截图20240816113800](https://github.com/user-attachments/assets/9d289bea-d6e2-4e4b-ac15-a62d31c9a330)

**Comment by NLick47** [comment]
可以这样修改
``` 
public static string FormatFileName(string originName)
 {
     var destName = originName;
     destName = Path.GetInvalidFileNameChars().Aggregate(destName, (current, c) => current.Replace(c.ToString(), string.Empty));

     var cleanedName = destName
            .SkipWhile(c => c == ' ' || c == '.')
            .Reverse()
            .SkipWhile(c => c == ' ' || c == '.')
            .Reverse()
            .ToArray();
     return new string(cleanedName.Length == 0 ? "[[empty title]]" : cleanedName);
 }

**Comment by yaobiao131** [comment]
> 可以这样修改
> 
> ``` 
> 
> public static string FormatFileName(string originName)
> 
>  {
> 
>      var destName = originName;
> 
>      destName = Path.GetInvalidFileNameChars().Aggregate(destName, (current, c) => current.Replace(c.ToString(), string.Empty));
> 
> 
> 
>      var cleanedName = destName
> 
>             .SkipWhile(c => c == ' ' || c == '.')
> 
>             .Reverse()
> 
>             .SkipWhile(c => c == ' ' || c == '.')
> 
>             .Reverse()
> 
>             .ToArray();
> 
>      return new string(cleanedName.Length == 0 ? "[[empty title]]" : cleanedName);
> 
>  }

可以提交pr，我测试后会合并进去

**Comment by yaobiao131** [comment]
由 https://github.com/yaobiao131/downkyicore/pull/139 修复
