### ISSUE TITLE
关闭重复下载提示

### ISSUE THREAD

**Issue by jl0476** [yaobiao131/downkyicore#130]
我经常用来批量下载收藏中的视频，每次点击下载全部即可。
现在每次都提示是否重复下载，其实是可以默认不重复下载的，请问是否可以增加一个开关，关闭重复下载提示。

**Comment by yaobiao131** [comment]
设置中已有相关设置





------------------ 原始邮件 ------------------
发件人: jl0476 ***@***.***&gt;
发送时间: 2024年8月17日 17:13
收件人: yaobiao131/downkyicore ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaobiao131/downkyicore] 关闭重复下载提示 (Issue #130)





 
我经常用来批量下载收藏中的视频，每次点击下载全部即可。
 现在每次都提示是否重复下载，其实是可以默认不重复下载的，请问是否可以增加一个开关，关闭重复下载提示。

**Comment by yaobiao131** [comment]
<img width="376" alt="image" src="https://github.com/user-attachments/assets/c9cd3e9f-4908-4841-abbd-90c2c1b91c6c">

**Comment by jl0476** [comment]
看到了 感谢！
