### ISSUE TITLE
下载的视频设置后没有序号

### ISSUE THREAD

**Issue by wdh200211** [yaobiao131/downkyicore#135]
如题  下载的视频设置后没有序号！设置如下 
![DownKyi文件名的设置方法](https://github.com/user-attachments/assets/0d80dfa5-8538-4808-8a57-463e87829bbc)
  

以前的版本设置后都可以按照视频有1 ， 2，3，4 一直向下的序号  现在如上设置后依然没有。请问是什么原因？是我设置的不对吗？

**Comment by yaobiao131** [comment]
你命名去掉了序号肯定没有得嘛

**Comment by wdh200211** [comment]
![图片](https://github.com/user-attachments/assets/b2a37147-fb3c-4afa-83e1-b82d95add7ab)
 经过以上设置后就可以按照视频顺序有1，2，3，4的序号了   感谢回答！！    但是我还是没有完全搞懂 文件命名格式  的详细用法！

**Comment by wdh200211** [comment]
![剪贴板图片](https://github.com/user-attachments/assets/c8dc5c82-85f9-4212-adae-264814c4da16)

经过以上设置后就可以按照视频顺序有1，2，3，4的序号了 感谢回答！！ 但是我还是没有完全搞懂 文件命名格式 的详细用法！

**Comment by yaobiao131** [comment]
可以自己舱室不同的文件命名，简单说就是你把上面的放在下面就是生成的文件名方式
