### ISSUE TITLE
Mac 下去水印闪退

### ISSUE THREAD

**Issue by Lumiaqian** [yaobiao131/downkyicore#14]
Mac 下去水印闪退，而且视频地址也没法从剪切板粘贴

**Comment by yaobiao131** [comment]
> Mac 下去水印闪退，而且视频地址也没法从剪切板粘贴

不要使用0作为任何一个参数。后续版本会修复闪退问题

**Comment by yaobiao131** [comment]
剪切板使用1.0.5版本就可以了
