### ISSUE TITLE
无法下载B站官方的合集视频

### ISSUE THREAD

**Issue by fs1314** [yaobiao131/downkyicore#141]
![QQ截图20240918121621](https://github.com/user-attachments/assets/a67da7bc-aaeb-4d9f-9d83-8e968d4d5e49)
![QQ截图20240918121611](https://github.com/user-attachments/assets/a7435744-d845-4e22-ac55-53776a546943)
如图，这种合集的视频里面一个都解析不出来。
图中的例子是av615209469

**Comment by yaobiao131** [comment]
这边测试是可以正常下载的
