### ISSUE TITLE
有的视频下载不了

### ISSUE THREAD

**Issue by ZX828** [yaobiao131/downkyicore#155]
BV1NTtxeGEKk
用1.0.10无法添加到下载列表
换成1.0.12
能添加到列表，但是下载失败
BV1NTtxeGEKk，这个视频没有收藏按钮诶，好奇怪的视频；

**Comment by yaobiao131** [comment]
<img width="1124" alt="image" src="https://github.com/user-attachments/assets/8674af45-e515-4422-869d-ac76a6533e6a">
这边测试正常

**Comment by ZX828** [comment]
1.0.12
一直这样，不动；
![image](https://github.com/user-attachments/assets/bd4aef0a-9fca-4802-bdbb-df597bf7fbf2)
开全局代理才可以，否则这个视频都显示不出来；
![image](https://github.com/user-attachments/assets/746b1e6f-e845-4c5f-be29-c6491f9e3471)


1.0.10
无法解析
![image](https://github.com/user-attachments/assets/cd11a355-040a-40a6-abdd-05acef625e64)

**Comment by ZX828** [comment]
刚刚才看到前几天更新了1.0.13
试了一下
![image](https://github.com/user-attachments/assets/8ccb12af-0caf-42ca-b16a-95d4f14b9be3)

**Comment by NLick47** [comment]
你开代理了吗，如果开了可以彻底关掉。再重新进软件试试

**Comment by ZX828** [comment]
我开着，关着，先开后关都试了。
感觉这个没有12稳定
