### ISSUE TITLE
1.0.12不能登录

### ISSUE THREAD

**Issue by ZX828** [yaobiao131/downkyicore#157]
1.0.12的登录二维码刷新不出来，需要开启全局代理才可以刷新出来；
登录之后，必须得一直开着代理，否则不能保持登录状态；

**Comment by Fo0o0oX** [comment]
+1 也遇到了这个问题

**Comment by MelanPrince** [comment]
同样不能登录 登录没有二维码。

**Comment by yaobiao131** [comment]
#151

**Comment by yaobiao131** [comment]
由[1.0.13](https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.13)修复，暂时关闭，如有问题可重新打开
