### ISSUE TITLE
【bug】二维码长时间无法正常加载

### ISSUE THREAD

**Issue by th10010** [yaobiao131/downkyicore#158]
![微信截图_20241014152318](https://github.com/user-attachments/assets/82496a30-3d94-41ff-87d1-304ff86ebe8e)
b站二维码长时间不能正常加载或者有时会显示加载超时，麻烦看下！

**Comment by yaobiao131** [comment]
#151

**Comment by yaobiao131** [comment]
由 #151 修复，下一版本发布
