### ISSUE TITLE
How to get this result?如何获得一下成果？

### ISSUE THREAD

**Issue by f2pmarathon** [yaobiao131/downkyicore#159]
![translating text](https://github.com/user-attachments/assets/45145aad-fdfd-40a8-9ecd-ae16b4f8cb71)

**Comment by f2pmarathon** [comment]
以前可以直接300+ 直接下载后直接看，现在全部分段只能一个一个看。

**Comment by yaobiao131** [comment]
I don't understand what you mean？没有明白你想表达什么

**Comment by f2pmarathon** [comment]
hi海外用户here。 是这样子的， 我只要copy 
https://www.bilibili.com/video/BV1XusfeMEtA/?spm_id_from=333.337.search-card.all.click&vd_source=5cd82f4cc646a1bb900de24e283f20d1

他就出来这个结果是列表的：
![translating text](https://github.com/user-attachments/assets/3fac2312-3854-4ad7-b4ab-6fc8bca3c98c)

可是我再要下载时就变成了这样

![image](https://github.com/user-attachments/assets/1b3a1122-a7e7-4ae4-951f-416626fe36cd)

**Comment by yaobiao131** [comment]
got it ,I will check soon

**Comment by f2pmarathon** [comment]
Thank you very much, because I only can watch offline video so I have to download first, the results show today is not table list, should download it all yesterday as it is one click solution only.

**Comment by yaobiao131** [comment]
That's correct, this link only has one video
<img width="1733" alt="image" src="https://github.com/user-attachments/assets/2fcaef25-005a-497c-b015-e9a0291f1593">

**Comment by f2pmarathon** [comment]
Thank you for your reply,but Monday the results I get is excel table list
with video quality and audio quality.
But I paste the same link at Tuesday it only shows 1 video. I want to
download all 400+ videos.

**Comment by yaobiao131** [comment]
This is not a software bug, it is now closed and you should search for the link again
