### ISSUE TITLE
为什么4K视频只能解析得到480P格式

### ISSUE THREAD

**Issue by 2022yingjie** [yaobiao131/downkyicore#160]
如图
![image](https://github.com/user-attachments/assets/c6ce9c4d-8998-4f85-94b5-e07dc129f7cc)

**Comment by yaobiao131** [comment]
你登录了吗？如果登录了还是没有4k可以吧链接发出来看一下

**Comment by iiaini** [comment]
是的，我也遇到了。番号BV1Z7mKYrERi

**Comment by 2022yingjie** [comment]
> 你登录了吗？如果登录了还是没有4k可以吧链接发出来看一下

登陆后解决了，thanks~
