### ISSUE TITLE
测试下载杜比音质的视频时，会出现下载后没有声音的情况

### ISSUE THREAD

**Issue by th10010** [yaobiao131/downkyicore#17]
选择4k画质，下载正常，视频也有声音
选择杜比视界，下载后，视频声音会丢失
案例视频：
https://www.bilibili.com/video/BV1YW4y1Y7qy/?spm_id_from=333.337.search-card.all.click&vd_source=79303edfc3b6146acf4a159ee2c34947
![1](https://github.com/yaobiao131/downkyicore/assets/55772277/dee86959-2f61-40f2-8508-31fba523da70)
![2](https://github.com/yaobiao131/downkyicore/assets/55772277/e4b15284-14ac-4480-81d1-20e3561a2701)

**Comment by th10010** [comment]
可以看出比特率不显示，且视频大小不如普通音质的视频

**Comment by yaobiao131** [comment]
问题已经由https://github.com/yaobiao131/downkyicore/commit/b009603dd855ae4d5842d7a43862aa9d96199379修复，将在下个版本
