### ISSUE TITLE
反馈两个bug

### ISSUE THREAD

**Issue by th10010** [yaobiao131/downkyicore#170]
1.列表选中不连贯，无论是ctrl+a全选列表还是鼠标用ctrl+shift一类的组合单独选，只能选中区域内的视频标题，区域外未显示的视频标题无法直接选中，需要手动选择。
![6](https://github.com/user-attachments/assets/e2b6afdc-bdcc-4230-9f4d-fcf2c44f57d8)
2.页面存在多个合集的，只能加载合计标题，不能加载合计下分集的标题。
![5](https://github.com/user-attachments/assets/892554f9-2b56-40e5-b62b-6b3e3e972b6d)
![4](https://github.com/user-attachments/assets/7fc1b908-f4d6-4979-a4e4-e62950742e8a)

**Comment by yaobiao131** [comment]
* 第一点由 https://github.com/yaobiao131/downkyicore/pull/162 修复，下次发布就会修复
* 第二点可以提供一下链接，我这边看能否解决

**Comment by th10010** [comment]
> * 第一点由 [fix: 修复合集选中 #162](https://github.com/yaobiao131/downkyicore/pull/162) 修复，下次发布就会修复
> * 第二点可以提供一下链接，我这边看能否解决

https://www.bilibili.com/video/BV1mS411w7dZ/?spm_id_from=333.788.videopod.sections&vd_source=db736b5569c24891fef76bf38bc2415c
