### ISSUE TITLE
合集bug

### ISSUE THREAD

**Issue by greenjail** [yaobiao131/downkyicore#173]
多个合集下，解析页面只显示合集，而不显示视频，例子如下
https://www.bilibili.com/video/BV1eo4y1u7aW
<img width="559" alt="image" src="https://github.com/user-attachments/assets/56a0f471-b0c3-4a15-b85c-0635a8b5c7c4">

**Comment by yaobiao131** [comment]
暂时没有适配多合集、后续研究一下

**Comment by 00exia00** [comment]
> 暂时没有适配多合集、后续研究一下

目前单个下面的横竖屏好像也有问题。
