### ISSUE TITLE
Ctrl+A无法全选   列表中   所有  视频，尤其是在  视频非常多的 专辑  中

### ISSUE THREAD

**Issue by nishilang** [yaobiao131/downkyicore#182]
Ctrl+A无法全选   列表中   所有  视频，尤其是在  视频非常多的 专辑  中，请大佬   修复一下

**Comment by yaobiao131** [comment]
提供一下测试链接

**Comment by zhiben5201** [comment]
> 提供一下测试链接

前几天用的13版本确实是这样的，即便点选全选，也只能选中窗口显示的这么多，下面的无法被选中，但今天更新了15版本之后测试了两个链接可以正常全选了，因此建议楼主更新一下最新版看看
