### ISSUE TITLE
手动解析无法解析，确实会失灵

### ISSUE THREAD

**Issue by zhiben5201** [yaobiao131/downkyicore#185]
手动解析无法解析，确实会失灵，看起来不是版本的问题，现在又出现了，模式无论选择解析当前页视频还是解析选中视频，即便勾选了自动解析也是无法解析的，试了很多链接都是这样，版本是最新的，也关闭重新开过还是一样。
已经进行过的尝试操作：1.更换数个链接
                                        2.更换三种解析模式
                                        3.切换自动手动解析
                                        4.升级主程序
                                        5.关闭主程序再开
                                        6.关闭主程序后手动在任务管理器结束aria2c.exe后再开
                                        7.重启路由器

**Comment by ShadowDevourer** [comment]
MacOS 版本同样出现了无法解析的问题，切无论手动还是自动解析都失败。

**Comment by yaobiao131** [comment]
我这边测试登录后可以正常解析

**Comment by zhiben5201** [comment]
> 我这边测试登录后可以正常解析

确实是不行，纯净重装软件之后只有第一次能正常解析，后续就都不行了

**Comment by fangxinsanlunai** [comment]
完全无法解析，是bilibili更新了新的加密码

**Comment by kjjohn** [comment]
过两小时又好了

**Comment by zhiben5201** [comment]
> 过两小时又好了

早上都不行

**Comment by yaobiao131** [comment]
麻烦测试下最新版本

**Comment by zhiben5201** [comment]
> 麻烦测试下最新版本

试了五六个链接是可以解析的

**Comment by chika0801** [comment]
> 麻烦测试下最新版本

刚刚测试了，已经恢复正常，感谢。

**Comment by cyril-wx** [comment]
怎么好的，我也更新了最新的，但是还是不能解析b站视频链接

**Comment by zhiben5201** [comment]
> 怎么好的，我也更新了最新的，但是还是不能解析b站视频链接

用最新的1.0.16版本，实在不行就干脆把现在用的版本彻底删除，然后重新安装最新版。确实已经好了，已经一天了
