### ISSUE TITLE
无法解析Hi-Res

### ISSUE THREAD

**Issue by KamierCola** [yaobiao131/downkyicore#196]
无法解析Hi-Res：会员扫码登录并且也勾选了Hi-Res音质，但是解析不出来，下载的也不是Hi-Res
![360截图20241223052713597](https://github.com/user-attachments/assets/8b6734d7-b995-471e-b814-375296a13acf)

**Comment by KamierCola** [comment]
临时用bilidown代替用了下能解析Hi-Res并下载真实，不知道代码能不能借鉴

![360截图20241223054515966](https://github.com/user-attachments/assets/eb51f8e4-46f7-4f64-b20b-f2adb50e8dd1)

**Comment by th10010** [comment]
一样的情况！！

**Comment by yaobiao131** [comment]
能提供一些hires的链接吗

**Comment by KamierCola** [comment]
> 能提供一些员工的链接吗

刚今天现在又试了下，现在好了能下载Hi-Res了。是不是今天代码优化过了，谢谢优化调整

**Comment by kardusenor** [comment]
> 能提供一些hires的链接吗

https://www.bilibili.com/video/BV1qW4y1G7GE/ 无法解析hires
