### ISSUE TITLE
下载解压后如何安装啊？

### ISSUE THREAD

**Issue by qifeibro** [yaobiao131/downkyicore#2]

**Comment by yaobiao131** [comment]
不需要安装，直接点击exe运行

**Comment by qifeibro** [comment]
> 不需要安装，直接点击exe运行

mac版啊

**Comment by yaobiao131** [comment]
mac直接运行DownKyi文件，自行安装.net6及以上运行库

**Comment by mubellyb** [comment]
> > > 不需要安装，直接点击exe运行
> > 
> > 
> > 我点击.exe后并不行啊
> 
> 自行安装.net6及以上运行库哈



> > > 不需要安装，直接点击exe运行
> > 
> > 
> > 我点击.exe后并不行啊
> 
> 自行安装.net6及以上运行库哈

大佬，我安装好了，但是视频一直显示卡在最后一步“正在混流”就是不成功。
![Uploading 屏幕截图 2023-12-03 223207.png…]()

**Comment by yaobiao131** [comment]
需要安装ffmpeg在环境变量path中。后面的版本我会优化下可以自行执行ffmpeg路径

**Comment by mubellyb** [comment]
> 需要安装ffmpeg在环境变量path中。后面的版本我会优化下可以自行执行ffmpeg路径

好的，已经可以正常使用了！

**Comment by qifeibro** [comment]
> mac直接运行DownKyi文件，自行安装.net6及以上运行库

安装完 .net6及以上运行库，也下载了DownKyi.1.0.0-beta.osx-x64.tar.gz 压缩包，解压后得到一堆dll文件

**Comment by qifeibro** [comment]
> * prefixed

dotnet run
Couldn't find a project to run. Ensure a project exists in /Users/jayce/Downloads/DownKyi.1.0.0-beta.osx-x64, or pass the path to the project using --project.
jayce@jayces-MacBook-Pro DownKyi.1.0.0-beta.osx-x64 %

**Comment by yaobiao131** [comment]
> > mac直接运行DownKyi文件，自行安装.net6及以上运行库
> 
> 大佬，我安装完 .net6及以上运行库，也下载了DownKyi.1.0.0-beta.osx-x64.tar.gz 压缩包，解压后得到一堆dll文件。里面没有 .csproj 文件
> 
> dotnet run Couldn't find a project to run. Ensure a project exists in /Users/jayce/Downloads/DownKyi.1.0.0-beta.osx-x64, or pass the path to the project using --project. jayce@jayces-MacBook-Pro DownKyi.1.0.0-beta.osx-x64 %

double click DownKyi to run it,i will pack to dmg in lastest version

**Comment by qifeibro** [comment]
> > > mac直接运行DownKyi文件，自行安装.net6及以上运行库
> 
> > 
> 
> > 大佬，我安装完 .net6及以上运行库，也下载了DownKyi.1.0.0-beta.osx-x64.tar.gz 压缩包，解压后得到一堆dll文件。里面没有 .csproj 文件
> 
> > 
> 
> > dotnet run Couldn't find a project to run. Ensure a project exists in /Users/jayce/Downloads/DownKyi.1.0.0-beta.osx-x64, or pass the path to the project using --project. jayce@jayces-MacBook-Pro DownKyi.1.0.0-beta.osx-x64 %
> 
> 
> 
> double click DownKyi to run it,i will pack to dmg in lastest version

OK，我还是等最新版吧。流下了没有技术的眼泪 ^_^

**Comment by BackMountainDevil** [comment]
linux(endeavouros) 测试下载视频可用

**Comment by yaobiao131** [comment]
https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.0

**Comment by qifeibro** [comment]
> https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.0

我mac是 os10.15的不支持，这个要求os11以上才行。还有办法解决吗？

**Comment by yaobiao131** [comment]
> > https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.0
> 
> 我mac是 os10.15的不支持，这个要求os11以上才行。还有办法解决吗？

有提示截图吗，.net6应该是支持10.15的

**Comment by qifeibro** [comment]
> > > https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.0
> > 
> > 
> > 我mac是 os10.15的不支持，这个要求os11以上才行。还有办法解决吗？
> 
> 有提示截图吗，.net6应该是支持10.15的

<img width="654" alt="Screen Shot 2023-12-19 at 9 01 11 PM" src="https://github.com/yaobiao131/downkyicore/assets/87322305/2eb4b854-1870-4609-a5dd-7a38a57186fe">

**Comment by yaobiao131** [comment]
> > > > https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.0
> > > 
> > > 
> > > 我mac是 os10.15的不支持，这个要求os11以上才行。还有办法解决吗？
> > 
> > 
> > 有提示截图吗，.net6应该是支持10.15的
> 
> <img alt="Screen Shot 2023-12-19 at 9 01 11 PM" width="654" src="https://private-user-images.githubusercontent.com/87322305/291757971-2eb4b854-1870-4609-a5dd-7a38a57186fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODg2MTIsIm5iZiI6MTcwMzA4ODMxMiwicGF0aCI6Ii84NzMyMjMwNS8yOTE3NTc5NzEtMmViNGI4NTQtMTg3MC00NjA5LWE1ZGQtN2EzOGE1NzE4NmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE2MDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZjZmYTdkZjI5MDEwNzNjMmZlMGE3ZTdlMTc4YzM1YWZiOWFkZDk3NTljM2Y2NThiYTY2NGI2N2FjMGZkNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eyctlSH-F9qF7Eeazmkxfts7MpTs6Pr3h5njOPdOSuk">

已发布新版已经支持

**Comment by qifeibro** [comment]
> > > > > https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.0
> > > > 
> > > > 
> > > > 我mac是 os10.15的不支持，这个要求os11以上才行。还有办法解决吗？
> > > 
> > > 
> > > 有提示截图吗，.net6应该是支持10.15的
> > 
> > 
> > <img alt="Screen Shot 2023-12-19 at 9 01 11 PM" width="654" src="https://private-user-images.githubusercontent.com/87322305/291757971-2eb4b854-1870-4609-a5dd-7a38a57186fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODg2MTIsIm5iZiI6MTcwMzA4ODMxMiwicGF0aCI6Ii84NzMyMjMwNS8yOTE3NTc5NzEtMmViNGI4NTQtMTg3MC00NjA5LWE1ZGQtN2EzOGE1NzE4NmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE2MDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZjZmYTdkZjI5MDEwNzNjMmZlMGE3ZTdlMTc4YzM1YWZiOWFkZDk3NTljM2Y2NThiYTY2NGI2N2FjMGZkNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eyctlSH-F9qF7Eeazmkxfts7MpTs6Pr3h5njOPdOSuk">
> 
> 已发布新版已经支持

这次是这样子了，
<img width="435" alt="Screen Shot 2023-12-20 at 3 07 27 PM" src="https://github.com/yaobiao131/downkyicore/assets/87322305/6cbac205-fcb6-4cdf-a515-f52176628204">

**Comment by yaobiao131** [comment]
> > > > > > https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.0
> > > > > 
> > > > > 
> > > > > 我mac是 os10.15的不支持，这个要求os11以上才行。还有办法解决吗？
> > > > 
> > > > 
> > > > 有提示截图吗，.net6应该是支持10.15的
> > > 
> > > 
> > > <img alt="Screen Shot 2023-12-19 at 9 01 11 PM" width="654" src="https://private-user-images.githubusercontent.com/87322305/291757971-2eb4b854-1870-4609-a5dd-7a38a57186fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODg2MTIsIm5iZiI6MTcwMzA4ODMxMiwicGF0aCI6Ii84NzMyMjMwNS8yOTE3NTc5NzEtMmViNGI4NTQtMTg3MC00NjA5LWE1ZGQtN2EzOGE1NzE4NmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE2MDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZjZmYTdkZjI5MDEwNzNjMmZlMGE3ZTdlMTc4YzM1YWZiOWFkZDk3NTljM2Y2NThiYTY2NGI2N2FjMGZkNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eyctlSH-F9qF7Eeazmkxfts7MpTs6Pr3h5njOPdOSuk">
> > 
> > 
> > 已发布新版已经支持
> 
> 这次是这样子了， <img alt="Screen Shot 2023-12-20 at 3 07 27 PM" width="435" src="https://private-user-images.githubusercontent.com/87322305/292007651-6cbac205-fcb6-4cdf-a515-f52176628204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzMyNzMsIm5iZiI6MTcwMzE3Mjk3MywicGF0aCI6Ii84NzMyMjMwNS8yOTIwMDc2NTEtNmNiYWMyMDUtZmNiNi00Y2RmLWE1MTUtZjUyMTc2NjI4MjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE1MzYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiN2UxYmM2OTRmMzMxMzk3YjZiZjg0NTY0ZWE3YmRkNTVmNzM3NWJhMTJhZThkM2MwNzg4MzgyMzEzZjVmMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9tFRil8JY_uJf0J_UnDQYi6Ex5xJKRfj-mF8sp2cFjw"> 点`？`后出现这个 <img alt="Screen Shot 2023-12-20 at 3 08 54 PM" width="480" src="https://private-user-images.githubusercontent.com/87322305/292008236-fd563898-1dda-4297-91b6-d09300fbe13f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzMyNzMsIm5iZiI6MTcwMzE3Mjk3MywicGF0aCI6Ii84NzMyMjMwNS8yOTIwMDgyMzYtZmQ1NjM4OTgtMWRkYS00Mjk3LTkxYjYtZDA5MzAwZmJlMTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE1MzYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZWRkOWFmOWM0YzlmMjYxZDBiZWU5NTUzZTFhNmY3NDkzYmZmOTYyZGM0N2U4YmFkYzIxZTgzNTc4ZjdkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pc7RYyErZHK8reS5OPgzmqf8ZK9HmNtjdzekE0uykJw"> 系统安全与隐私那里也没有提示打开

这个你需要自行去找一下如何运行未签名程序。应该很好找
