### ISSUE TITLE
下次登入无法保存未下载的列表和选定要下载的列表无效-bug

### ISSUE THREAD

**Issue by hermitguo** [yaobiao131/downkyicore#200]
环境：win11-24h2

1、下次登入无法保存未下载的列表，会被清空
2、解析后的视频，按shift 键选定需要下载的列表，无效，结果默认选择所有的列表，可能前面没有复选框导致

注：原版本下载姬不会，目前突然发现原版登入，没有显示扫描的二维码，可能没有维护的原因，所以搜索到这里

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added shift-click selection functionality and implemented saving of undownloaded list.

You can review changes in this commit: https://github.com/mark-addams001881/yaobiao131-downkyicore-200/commit/6a1d245a7bf0ab0f864ed260274751a36a7be5dc.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by hermitguo** [comment]
Thank you very much
