### ISSUE TITLE
希望下载重复文件时增加第三个选项 “为重复的下载链接添加带序号的文件名”

### ISSUE THREAD

**Issue by pm-yangtz** [yaobiao131/downkyicore#21]
【场景】：抓取up所有投稿视频直接全选并批量下载
【问题】：如果出现多个同名文件，会后下载的会自动覆盖前一个。例如第一个下载的是 “2024-1-26录像”，后续又下载了另一个“2024-1-26录像”，两个名称完全相同，但内容时长、文件大小均不同。
点击下载时，软件会提示重复，只能选放弃下载（保留原有，新的不下载）或重新下载（覆盖已存在的文件）没办法两者并存。
【期望与建议】：
希望增加第三个选项 “为重复的下载链接添加带序号的文件名”。如“2024-1-26录像”、“2024-1-26录像_1”、“2024-1-26录像_2”。
这样多文件并存后，用户可根据个人需要进行后续查重或选择多副本并存等处理方式。

**Comment by pm-yangtz** [comment]
就是【下载选中项】的【是】（覆盖已存在的文件）与【否】（保留原有，新的不下载）都不是我想要的。

**Comment by yaobiao131** [comment]
对于你说的可以提供一下重复名字的视频链接吗，我这边好测试一下

**Comment by pm-yangtz** [comment]
感谢您百忙之中的回复。
【复现1-单个链接分别下载】：不会有提示，软件内显示两个均已下载，实际本地存储一个。
【视频1】https://www.bilibili.com/video/BV1PK4y1q7FR/
【视频2】https://www.bilibili.com/video/BV1ba4y1C7u6/
![图片](https://github.com/yaobiao131/downkyicore/assets/101697330/69dac98c-e51a-4974-94a5-73e8dddd6bca)
![图片](https://github.com/yaobiao131/downkyicore/assets/101697330/642b02db-deb4-4f32-819f-7e7489c54a9a)
【复现2-从up主页勾选下载（已清空本地和下载记录）】：实际还是保存一个
【主页】https://space.bilibili.com/52945205/video
![图片](https://github.com/yaobiao131/downkyicore/assets/101697330/3e404ddb-c19f-4d14-8350-c86722b8a6d8)
![图片](https://github.com/yaobiao131/downkyicore/assets/101697330/e0babd3c-fb0d-4822-b0d3-b31758a702c1)
![图片](https://github.com/yaobiao131/downkyicore/assets/101697330/24dddd48-753c-4a9b-8d8d-b7599eeb89fa)
（另外今天复测时点击【下载选中项】没有关于重复的提示了。可能是我误触了默认选项，被找到在哪恢复）

**Comment by yaobiao131** [comment]
默认命名的话确实会覆盖，你暂时可以在设置里面修改下命名方式，比如加上一些一定不一样的命名(avid,bvid,cid,发布时间等等)

**Comment by pm-yangtz** [comment]
感谢。
实测发布时间只精确到天，bvid不方便批量重命名,
avid,cid这两个目前字符长度固定，可使用批量重命名工具后续自行操作。

**Comment by pm-yangtz** [comment]
【自动去水印】
请问下开发者可以把自动去除【bilibili】平台的功能修复吗？对比了下downkyi 老版本1.5.9时下载的视频，会自动去处平台水印，现在下载后带水印。（不知道是平台问题还是软件功能问题，就不提新的 lssues 了）。
![图片](https://github.com/yaobiao131/downkyicore/assets/101697330/dfd7012a-4d8c-47d4-bc60-7e205c8e8f31)
![图片](https://github.com/yaobiao131/downkyicore/assets/101697330/152c78c6-093c-4cb2-ae9f-548e31c0e02e)

**Comment by yaobiao131** [comment]
1.5.9的代码我也看过没有自动去水印哈，只有手动





------------------ 原始邮件 ------------------
发件人: 小杨 ***@***.***&gt;
发送时间: 2024年1月29日 16:36
收件人: yaobiao131/downkyicore ***@***.***&gt;
抄送: yaobiao131 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaobiao131/downkyicore] 希望下载重复文件时增加第三个选项 “为重复的下载链接添加带序号的文件名” (Issue #21)





 
【自动去水印】
 请问下开发者可以把自动去除【bilibili】平台的功能修复吗？对比了下downkyi 老版本1.5.9时下载的视频，会自动去处平台水印，现在下载后带水印。（不知道是平台问题还是软件功能问题，就不提新的 lssues 了）。
 default.png (view on web)
 default.png (view on web)
