### ISSUE TITLE
卡音频下载

### ISSUE THREAD

**Issue by Tenadults** [yaobiao131/downkyicore#23]
<img width="749" alt="{A774CB41-D27E-4a09-91D4-196C8E8E3A7D}" src="https://github.com/yaobiao131/downkyicore/assets/60803919/bcd4a38b-e908-4643-8897-fa86d02fb265">

这个用的时候一直卡在音频下载这个地方，之后过了一段时间后就会显示下载失败，不知道是什么原因

**Comment by yaobiao131** [comment]
可以提供一下日志和下载的视频链接吗





------------------ 原始邮件 ------------------
发件人: 峻熙 ***@***.***&gt;
发送时间: 2024年1月29日 00:10
收件人: yaobiao131/downkyicore ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaobiao131/downkyicore] 卡音频下载 (Issue #23)





 A774CB41-D27E-4a09-91D4-196C8E8E3A7D.png (view on web) 
这个用的时候一直卡在音频下载这个地方，之后过了一段时间后就会显示下载失败，不知道是什么原因

**Comment by Tenadults** [comment]
> 可以提供一下日志和下载的视频链接吗
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 峻熙 ***@***.***&gt; 发送时间: 2024年1月29日 00:10 收件人: yaobiao131/downkyicore ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [yaobiao131/downkyicore] 卡音频下载 (Issue #23) A774CB41-D27E-4a09-91D4-196C8E8E3A7D.png (view on web) 这个用的时候一直卡在音频下载这个地方，之后过了一段时间后就会显示下载失败，不知道是什么原因 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

[Uploading 20240130(0).log…]()

**Comment by Tenadults** [comment]
> 可以提供一下日志和下载的视频链接吗
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 峻熙 ***@***.***&gt; 发送时间: 2024年1月29日 00:10 收件人: yaobiao131/downkyicore ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [yaobiao131/downkyicore] 卡音频下载 (Issue #23) A774CB41-D27E-4a09-91D4-196C8E8E3A7D.png (view on web) 这个用的时候一直卡在音频下载这个地方，之后过了一段时间后就会显示下载失败，不知道是什么原因 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

[20240130(0).log](https://github.com/yaobiao131/downkyicore/files/14099140/20240130.0.log)
不知道是什么原因，我下载什么视频好像都不行，不是特定的某一个视频不能下

**Comment by yaobiao131** [comment]
看日志，你dns无法连接b站视频服务器

**Comment by Tenadults** [comment]
> 看日志，你dns无法连接b站视频服务器

后面我试着把dns改成8.8.8.8后可以了
