### ISSUE TITLE
部分视频下载分辨率有问题

### ISSUE THREAD

**Issue by FadeJay** [yaobiao131/downkyicore#26]
BV1JN4y1v7vE，解析下来是画质是有1080p高码率的，但当下载后面发现视频分辨率为1682x830，选择音质高质量，画质1080p高码率，视频编码H.264/AVC

**Comment by FadeJay** [comment]
试了下H.265/HEVC和AVC编码下载下来分辨率是正常的

**Comment by yaobiao131** [comment]
这个视频如果你在B站使用avc也是1682x830，所以没有问题
