### ISSUE TITLE
视频下载画质和编码设置无法保存

### ISSUE THREAD

**Issue by 897601689** [yaobiao131/downkyicore#3]
设置8k 重新进入发现又变回4k了

**Comment by yaobiao131** [comment]
是设置里面的默认画质是吧

**Comment by 897601689** [comment]
我的设置
![Snipaste_2023-12-21_10-37-28](https://github.com/yaobiao131/downkyicore/assets/20634089/a6773f24-7b23-4034-a23c-9ad74f709c6f)
点击左侧任意信息 再次进入视频设置 设置信息就又恢复默认了
![Snipaste_2023-12-21_10-37-37](https://github.com/yaobiao131/downkyicore/assets/20634089/89f15ecb-aa92-4787-8e60-e31624c7225a)

**Comment by 897601689** [comment]
默认的编码。画质 音质 都无法改变

**Comment by yaobiao131** [comment]
了解了，感谢测试
