### ISSUE TITLE
下载了新版v1.0.7 打不开，但旧版v1.0.6 可以正常使用，电脑系统win7

### ISSUE THREAD

**Issue by 4399LX** [yaobiao131/downkyicore#31]
下载了新版v1.0.7 打不开，但旧版v1.0.6 可以正常使用。

测试电脑系统win7 打不开，
测试电脑系统win10 正常打开。

![截图2024-02-05_220747](https://github.com/yaobiao131/downkyicore/assets/155865983/ed10feb6-c5d4-4d06-9cd1-02c0dfa37132)

为什么呢，是因为删掉了新版v1.0.7 描述中的东西吗？

Miscellaneous Tasks
去掉rpm arm64构建
去掉rpm arm64构建

**Comment by 4399LX** [comment]
但我windows 7 确实打不开啊？

**Comment by yaobiao131** [comment]
修复了，稍后我替换下windows的release

**Comment by 4399LX** [comment]
好的，不过现在已经很晚了，我明天再试
