### ISSUE TITLE
只能下载480p分辨率

### ISSUE THREAD

**Issue by Haofuuu** [yaobiao131/downkyicore#32]
下载的是1.0.7 arm64版本的
试了好多个4k视频，解析出来显示只有480p，下载下来也确实只有480p
如图
<img width="1440" alt="Screenshot 2024-02-05 at 8 31 04 PM" src="https://github.com/yaobiao131/downkyicore/assets/158782867/357f9d86-9f97-43e0-9e73-35e148a5aaaa">
<img width="1440" alt="Screenshot 2024-02-05 at 8 31 12 PM" src="https://github.com/yaobiao131/downkyicore/assets/158782867/a73158bd-1007-417a-bb20-23897f4ecbff">

**Comment by yaobiao131** [comment]
有空我会排查一下





------------------ 原始邮件 ------------------
发件人: Haofuuu ***@***.***&gt;
发送时间: 2024年2月6日 09:34
收件人: yaobiao131/downkyicore ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaobiao131/downkyicore] 只能下载480p分辨率 (Issue #32)





 
下载的是1.0.7 arm64版本的
 试了好多个4k视频，解析出来显示只有480p，下载下来也确实只有480p
 如图
 Screenshot.2024-02-05.at.8.31.04.PM.png (view on web)
 Screenshot.2024-02-05.at.8.31.12.PM.png (view on web)

**Comment by yaobiao131** [comment]
> 下载的是1.0.7 arm64版本的 试了好多个4k视频，解析出来显示只有480p，下载下来也确实只有480p 如图 <img alt="Screenshot 2024-02-05 at 8 31 04 PM" width="1440" src="https://private-user-images.githubusercontent.com/158782867/302474289-357f9d86-9f97-43e0-9e73-35e148a5aaaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxODQ5NTcsIm5iZiI6MTcwNzE4NDY1NywicGF0aCI6Ii8xNTg3ODI4NjcvMzAyNDc0Mjg5LTM1N2Y5ZDg2LTlmOTctNDNlMC05ZTczLTM1ZTE0OGE1YWFhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwMTU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDIxYzZjMTZlZDE0Zjk1YTQ0MGE5OWU2YTM0NjU2N2VhOTMxNWExZmJhYmIxMTg4YWUyM2ZlZTlhNTk2YjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZRcacCVlLjjzlK-D0boPcZmfUPSNJFAQV6we7YEjgEs"> <img alt="Screenshot 2024-02-05 at 8 31 12 PM" width="1440" src="https://private-user-images.githubusercontent.com/158782867/302474294-a73158bd-1007-417a-bb20-23897f4ecbff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxODQ5NTcsIm5iZiI6MTcwNzE4NDY1NywicGF0aCI6Ii8xNTg3ODI4NjcvMzAyNDc0Mjk0LWE3MzE1OGJkLTEwMDctNDE3YS1iYjIwLTIzODk3ZjRlY2JmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwMTU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTczMWMxOTRlMjU3YjY4MzA0ZmQ5N2ViNWY4YWMzNzBiOGU1NGEzN2U5Y2VjMTk0N2M1NzNmZWE2ZWY1YTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jigOALWY3-6-ZxOwDywWnK1M7mOZkdOMUiX759mjthM">

1080p需要登录才能解析，先确认是否登录

**Comment by Haofuuu** [comment]
哦哦需要登录是吗，我试试，谢谢！
