### ISSUE TITLE
解析500左右就解析不出来了下载也会失败

### ISSUE THREAD

**Issue by RuoShuigogo** [yaobiao131/downkyicore#36]
![Snipaste_2024-02-16_22-20-48](https://github.com/yaobiao131/downkyicore/assets/142558307/f4b80351-a7d0-4d1c-94bc-3c6c1be1bdfb)

**Comment by RuoShuigogo** [comment]
主要是这个她分了1000个p没办法一次性解析完就比较难受

**Comment by yaobiao131** [comment]
> 主要是这个她分了1000个p没办法一次性解析完就比较难受

可以提供一下视频链接吗，我这边测试下这么多p的视频

**Comment by RuoShuigogo** [comment]
https://www.bilibili.com/video/BV1d64y197gj/

**Comment by niiickelback** [comment]
兄弟这是要卖课去么

**Comment by pm-yangtz** [comment]
一次解析300左右比较稳，我下载有些切片也是8/900一个合集。分次下吧，可能是B站对接口调用的限制，曾一天下载了1500P左右，直接全网（PC+手机+downkyi）登出账号，验证手机号重登就没事了。
