### ISSUE TITLE
采用复制主页进行批量下载的时候，经常下载两三页就没法下载，全部下载失败

### ISSUE THREAD

**Issue by zhiben5201** [yaobiao131/downkyicore#37]
采用复制主页进行批量下载的时候，经常下载两三页就没法下载，全部下载失败，还会频繁闪退，重试，重启程序，重新添加下载任务，改端口都无效，有什么解决办法吗

**Comment by yaobiao131** [comment]
https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.8
