### ISSUE TITLE
新版添加的自动添加后缀功能还是无法使用

### ISSUE THREAD

**Issue by Lacus-Clyne** [yaobiao131/downkyicore#38]
很迷，提示设置已更新但是遇到名称冲突的文件，新的还是会覆盖旧的，重启软件后其他设置都能正常保存唯独这个选项不能。
<img width="818" alt="屏幕截图 2024-02-23 083725" src="https://github.com/yaobiao131/downkyicore/assets/20676724/b7fa7528-61b3-4c11-a5b9-3f7b29c4f375">

**Comment by yaobiao131** [comment]
最新提交已经修复，下一版本发布哈

**Comment by Lacus-Clyne** [comment]
辛苦了

**Comment by yaobiao131** [comment]
https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.8
