### ISSUE TITLE
下载中未完成时暂停下载，重启后恢复下载

### ISSUE THREAD

**Issue by 84531956** [yaobiao131/downkyicore#39]
发现个很有意思的事情：打开1个客户端会出现下载未完成时暂停下载的情况，然后重启客户端又能继续下载了。但是在我无意中打开第二个客户端的时候有意思的事情发生了，第一个暂停的客户端既然恢复下载了。这是因为客户端知道自己在偷偷的下载，一个害怕需要再来一个壮壮胆吗。一个干活一个守护。
这应该算是个bug？！

**Comment by yaobiao131** [comment]
https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.8
已发布仅允许运行一个实例的版本

**Comment by 84531956** [comment]
<img width="926" alt="1709774627369" src="https://github.com/yaobiao131/downkyicore/assets/152254928/410164e6-712e-4ff2-a0df-e759b82812bb">
我这里还是可以打开呢!单独打开一个打不开，但是在下载期间就可以打开好多个了！不过不影响什么功能，反而打开第二个下载更顺畅了！
