### ISSUE TITLE
解析视频后下载进度一直为0

### ISSUE THREAD

**Issue by Jacy-CeheYun** [yaobiao131/downkyicore#40]
今天开始突然解析视频后无法正常下载视频，音频也无法下载，日志中提示error如下
2024/2/23 16:32:59   [15]   DEBUG   AriaServer  02/23 16:32:59 [[1;31mERROR[0m] CUID#22 - Download aborted. URI=https://upos-sz-mirrorali.bilivideo.com/upgcxcode/10/44/9094410/9094410_da3-1-30064.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1708684232&gen=playurlv2&os=alibv&oi=3735888906&trid=cc50acb5434e4ca9ae4be855236193d3u&mid=5357435&platform=pc&upsig=c2962c76e26025db3d2902f5815c9283&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=2,3&buvid=&build=0&f=u_0_0&agrr=1&bw=30264&logo=40000000
----------------------------------------------------------------------------------------------------------------------
2024/2/23 16:32:59   [15]   DEBUG   AriaServer  Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://upos-sz-mirrorali.bilivideo.com/upgcxcode/10/44/9094410/9094410_da3-1-30064.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1708684232&gen=playurlv2&os=alibv&oi=3735888906&trid=cc50acb5434e4ca9ae4be855236193d3u&mid=5357435&platform=pc&upsig=c2962c76e26025db3d2902f5815c9283&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=2,3&buvid=&build=0&f=u_0_0&agrr=1&bw=30264&logo=40000000
----------------------------------------------------------------------------------------------------------------------
 ERROR   AriaManager  CUID#22 - Name resolution for upos-sz-mirrorali.bilivideo.com failed:Timeout while contacting DNS servers

**Comment by yaobiao131** [comment]
日志显示你的网络问题，dns解析失败
