### ISSUE TITLE
下载多个带字幕的视频时容易卡住

### ISSUE THREAD

**Issue by pm-yangtz** [yaobiao131/downkyicore#41]
【场景】：视频为合集，且带有自动生成的字幕（up上传英文再B站自动翻译）
【问题】：下载部分视频后，会卡住，显示【字幕下载中】，需要点击【暂停】，再点击【开始】，即可继续下载。问题多次复现
【测试链接】https://www.bilibili.com/video/BV1PS421N7j9/
【使用版本】1.0.6（升级1.0.7后如果勾选新增的“重复视频添加序号类的新功能，下载视频时直接闪退，所以回退“1.0.6”，但没看其他人提可能与我的本机环境有关，下个版本再试试。）

![图片](https://github.com/yaobiao131/downkyicore/assets/101697330/4384e780-de0a-49b3-8aee-71b5fd3a09dc)

**Comment by pm-yangtz** [comment]
点错了

**Comment by 84531956** [comment]
【反馈】没什么问题，用1.07版本(UA:Mozilla/5.0)可以正常下载视频和字幕文件
【新问题】字幕为独立文件，我用potPlayer播放视频，字幕没有主动加载（手动加载后可以正常播放字幕）。
【测试环境】Y9000P 2023(i9+16+1+4060)|win11 23H2|.net3.5|runtime6.03|vc++(2008 2012 2015-2022)
【建议】可以打开两个DownKyi1.07，一个下载，另外一个什么都不干，测试一下会不会还暂停下载（偶然机会我发现第一个暂停了下载后，再打开另一个，第一个会重新开始下载并且不会再出现下载暂停，测试一下，不能保证你的也有效）。
