### ISSUE TITLE
1.07版打开video页奔溃

### ISSUE THREAD

**Issue by renmenziji** [yaobiao131/downkyicore#42]
1.07版打开video页奔溃https://space.bilibili.com/625267185/video

**Comment by renmenziji** [comment]
如上所示，1.6.1也是如此

**Comment by yaobiao131** [comment]
<img width="1109" alt="image" src="https://github.com/yaobiao131/downkyicore/assets/28655758/a089ac33-12eb-45d5-91ce-bbcb1eefd605">

**Comment by renmenziji** [comment]
感谢测试，我使用的是DownKyi-1.0.7-1.win-x64版本。再次在一台新电脑上测试，依旧奔溃！

**Comment by yaobiao131** [comment]
windows上面确实有问题，我排查一下





------------------ 原始邮件 ------------------
发件人: renmenziji ***@***.***&gt;
发送时间: 2024年3月5日 14:33
收件人: yaobiao131/downkyicore ***@***.***&gt;
抄送: yaobiao131 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [yaobiao131/downkyicore] 1.07版打开video页奔溃 (Issue #42)





 
感谢测试，我使用的是DownKyi-1.0.7-1.win-x64版本。再次在一台新电脑上测试，依旧奔溃！

**Comment by yaobiao131** [comment]
初步发现是因为b站风控。使用用户主页下载登录后就正常了

**Comment by renmenziji** [comment]
感谢测试，登录了的确可以打开了，感谢！
