### ISSUE TITLE
关于Windows端文件命名问题

### ISSUE THREAD

**Issue by lisansas** [yaobiao131/downkyicore#43]
从原版转过来后发现一些视频重复下载了，经过确认是命名的问题。

原版里在Windows端 "/" "|”会自动转换为空格，而这个版本会直接去掉/和|等

举个例子
原视频为
![图片](https://github.com/yaobiao131/downkyicore/assets/38862056/be3709be-1e75-4148-beea-2b7773e664c0)
![图片](https://github.com/yaobiao131/downkyicore/assets/38862056/489a526a-24e4-477f-8421-d2911e11cba9)
这是两个版本视频名称的差别.

**Comment by yaobiao131** [comment]
能提供一下两个重复视频的链接吗

**Comment by lisansas** [comment]
BV1bG411z7t8 这个是|
BV1m44y1F7r8 这个是/

**Comment by yaobiao131** [comment]
> BV1bG411z7t8 这个是| BV1m44y1F7r8 这个是/

这两个视频不会重复吧

**Comment by lisansas** [comment]
> > BV1bG411z7t8 这个是| BV1m44y1F7r8 这个是/
> 
> 这两个视频不会重复吧

我两个软件文件命名都是全默认的，很多重复的，包括我发的这两个。

全都是downkyicore在Windows端的命名怪怪的.

![图片](https://github.com/yaobiao131/downkyicore/assets/38862056/66eb8b04-8b53-4038-a21a-8dfbce32586c)
![图片](https://github.com/yaobiao131/downkyicore/assets/38862056/e306d549-4cc7-4245-8415-87085186d521)
![图片](https://github.com/yaobiao131/downkyicore/assets/38862056/9927bd3e-b973-4829-83b1-5fbfcfe30657)

**Comment by yaobiao131** [comment]
两个软件要不一样的下载路径，重复无法共同判断

**Comment by lisansas** [comment]
> 两个软件要不一样的下载路径，重复无法共同判断

我懂了，我原来以为这个\ |的转换是bug，因为空格或者-或者不改都比较美观，看来是为了跨平台应用而做的处理。
