### ISSUE TITLE
mac m1 下载失败

### ISSUE THREAD

**Issue by B1D1ng** [yaobiao131/downkyicore#47]
视频可以正常解析，但是一下载就秒失败，网络切换什么的都尝试过

**Comment by yaobiao131** [comment]
麻烦附上日志文件

**Comment by B1D1ng** [comment]
> 麻烦附上日志文件

请问在哪里获取？

**Comment by yaobiao131** [comment]
> > 麻烦附上日志文件
> 
> 请问在哪里获取？

~/Library/Application Support/DownKyi/ 里面的Logs文件夹

**Comment by B1D1ng** [comment]
> > > 麻烦附上日志文件
> > 
> > 
> > 请问在哪里获取？
> 
> ~/Library/Application Support/DownKyi/ 里面的Logs文件夹

日志只记录到解析成功，下载操作没有记录上，重新打开软件，第一次下载的时候UI上的下载进度条一直是空白卡着不动，然后点击重试直接显示下载失败，下载操作的所有行为日志都没有记录上
[20240307(0).log](https://github.com/yaobiao131/downkyicore/files/14518794/20240307.0.log)
<img width="1090" alt="WX20240307-123703@2x" src="https://github.com/yaobiao131/downkyicore/assets/31911710/a5e9d46f-b05f-4395-8aa5-a2a8f012ff2a">

**Comment by yaobiao131** [comment]
> > > > 麻烦附上日志文件
> > > 
> > > 
> > > 请问在哪里获取？
> > 
> > 
> > ~/Library/Application Support/DownKyi/ 里面的Logs文件夹
> 
> 日志只记录到解析成功，下载操作没有记录上，重新打开软件，第一次下载的时候UI上的下载进度条一直是空白卡着不动，然后点击重试直接显示下载失败，下载操作的所有行为日志都没有记录上 [20240307(0).log](https://github.com/yaobiao131/downkyicore/files/14518794/20240307.0.log) <img alt="WX20240307-123703@2x" width="1090" src="https://private-user-images.githubusercontent.com/31911710/310747829-a5e9d46f-b05f-4395-8aa5-a2a8f012ff2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODY2MDEsIm5iZiI6MTcwOTc4NjMwMSwicGF0aCI6Ii8zMTkxMTcxMC8zMTA3NDc4MjktYTVlOWQ0NmYtYjA1Zi00Mzk1LThhYTUtYTJhOGYwMTJmZjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA0MzgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NzE1NzY0ZTMzZmNhZWRiZGJlOTQyZTBjYmQzNGUxZmZlYjYxNjIzYjNlNjVhNTIzYTA3NDUzNDJhMzFjMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D3Io73xaEqvGq3UH065Kww3QnxcREtyMzFwQvsuxiVg">

目录下面还有aria2的日志可以看一下

**Comment by B1D1ng** [comment]
> > > > > 麻烦附上日志文件
> > > > 
> > > > 
> > > > 请问在哪里获取？
> > > 
> > > 
> > > ~/Library/Application Support/DownKyi/ 里面的Logs文件夹
> > 
> > 
> > 日志只记录到解析成功，下载操作没有记录上，重新打开软件，第一次下载的时候UI上的下载进度条一直是空白卡着不动，然后点击重试直接显示下载失败，下载操作的所有行为日志都没有记录上 [20240307(0).log](https://github.com/yaobiao131/downkyicore/files/14518794/20240307.0.log) <img alt="WX20240307-123703@2x" width="1090" src="https://private-user-images.githubusercontent.com/31911710/310747829-a5e9d46f-b05f-4395-8aa5-a2a8f012ff2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODY2MDEsIm5iZiI6MTcwOTc4NjMwMSwicGF0aCI6Ii8zMTkxMTcxMC8zMTA3NDc4MjktYTVlOWQ0NmYtYjA1Zi00Mzk1LThhYTUtYTJhOGYwMTJmZjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA0MzgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NzE1NzY0ZTMzZmNhZWRiZGJlOTQyZTBjYmQzNGUxZmZlYjYxNjIzYjNlNjVhNTIzYTA3NDUzNDJhMzFjMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D3Io73xaEqvGq3UH065Kww3QnxcREtyMzFwQvsuxiVg">
> 
> 目录下面还有aria2的日志可以看一下

aria log 0字节，没有记录

**Comment by yaobiao131** [comment]
那就是你aria2没启动成功，你切换内置下载器试试

**Comment by B1D1ng** [comment]
> 那就是你aria2没启动成功，你切换内置下载器试试

切换后好像可以了，显示音频下载中，但是进度条

> 那就是你aria2没启动成功，你切换内置下载器试试

解决了，感谢解答！
