### ISSUE TITLE
除了大部分设置无法保存，还有我点我空间的稍后再看，闪退或无响应

### ISSUE THREAD

**Issue by 1983sxj** [yaobiao131/downkyicore#5]
除了大部分设置无法保存，还有我点我空间的稍后再看，闪退或无响应

**Comment by yaobiao131** [comment]
设置可以说明一下哪些吗，稍后再看已经修复，今晚会发布

**Comment by 1983sxj** [comment]
> 设置可以说明一下哪些吗，稍后再看已经修复，今晚会发布

厄，“基本”那一页，然后“视频”优先下载的3行，“弹幕”那一页
另外“基本”那一页貌似解析一次就能保存，但是在“基本”这个设置也无法保存
