### ISSUE TITLE
下载b站视频时候 音频只有最后有几秒成功合并 前面都没有声音

### ISSUE THREAD

**Issue by Lin-Buji** [yaobiao131/downkyicore#53]
我这里显示下载成功了 但是他视频播放时候我发现只有最后几秒才有声音 不知道为什么？
这是url：https://www.bilibili.com/video/BV17F411T7Ao?p=1
![image](https://github.com/yaobiao131/downkyicore/assets/109971993/0bc72184-c0ce-46e1-8e41-e7d5501aec2f)

**Comment by yaobiao131** [comment]
我会测试下

**Comment by Lin-Buji** [comment]
期待大佬的测试 我的操作是只下载了音频 视频 封面 其他的没有选 然后解析视频 最后下载 用potplayer播放只有最后几秒有声音~期待大佬的测试 ！

**Comment by yaobiao131** [comment]
我这边的测试没有问题
