### ISSUE TITLE
下载不了

### ISSUE THREAD

**Issue by liuchenmao** [yaobiao131/downkyicore#54]
可以解析了,但还是下载不了视频,会闪退

**Comment by yaobiao131** [comment]
请提供日志文件

**Comment by liuchenmao** [comment]
> 请提供日志文件

[DownKyi.zip](https://github.com/yaobiao131/downkyicore/files/14614790/DownKyi.zip)
这个嘛

**Comment by liuchenmao** [comment]
> 请提供日志文件

大佬知道原因了吗

**Comment by yaobiao131** [comment]
是软件目录下面的Logs文件夹里面的日志，或者事件管理器里面查看一下闪退原因

**Comment by liuchenmao** [comment]
[20240316(0).log](https://github.com/yaobiao131/downkyicore/files/14623433/20240316.0.log)


> 是软件目录下面的Logs文件夹里面的日志，或者事件管理器里面查看一下闪退原因

**Comment by yaobiao131** [comment]
日志暂时看不出原因，可以看一下事件管理器里面的错误
