### ISSUE TITLE
[bug] When pressing "download all chosen", all parsing items will be download | 当”下载所选项“时，实际下载的是全部已解析项

### ISSUE THREAD

**Issue by RainoutOvO** [yaobiao131/downkyicore#63]
Using [v1.0.8](https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.8), win x64.
This is extremely terrible, I hope to be fixed soon.

问题版本 [v1.0.8](https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.8), 设备环境 win x64.
希望这个问题会被尽快修复。

**Comment by yaobiao131** [comment]
已经修复了，下个版本发布

**Comment by yaobiao131** [comment]
已发布
