### ISSUE TITLE
最近感觉弹幕下载不正常

### ISSUE THREAD

**Issue by 1983sxj** [yaobiao131/downkyicore#68]
最近感觉弹幕下载不正常，于是刚刚试了一下
是最新版的1.0.8
找个新视频试了试
BV1Wr421b7je
附上Log和弹幕
downkyicore未屏蔽任何弹幕，B站我也没屏蔽任何弹幕
压缩包里1是downkyicore下载的弹幕，2是插件Bilibili Evolved下载的弹幕
2基本上是1的弹幕数量的2倍左右吧

之前我记得有些弹幕更多的视频，下载下来更夸张，可能差距达到只剩10分之一左右这样子

不是什么大问题，大佬有空看看，没空看就算了，感谢

[20240329(0).log](https://github.com/yaobiao131/downkyicore/files/14805256/20240329.0.log)
[弹幕.zip](https://github.com/yaobiao131/downkyicore/files/14805265/default.zip)

**Comment by yaobiao131** [comment]
https://github.com/yaobiao131/downkyicore/commit/4243f50866609640c362a695da16d5fbfe958d39 已修复 发布版还没有修复弹幕问题，等待下次发布

**Comment by 1983sxj** [comment]
> [4243f50](https://github.com/yaobiao131/downkyicore/commit/4243f50866609640c362a695da16d5fbfe958d39) 已修复 发布版还没有修复弹幕问题，等待下次发布

好的感谢修复

**Comment by yaobiao131** [comment]
已发布
