### ISSUE TITLE
大佬，1.0.2视频会卡在混流中，1.0.1不会

### ISSUE THREAD

**Issue by th10010** [yaobiao131/downkyicore#7]
1.02下载视频后进度一直卡在混流中，视频不大，但是卡了十多分钟都没反应
![20231222193525](https://github.com/yaobiao131/downkyicore/assets/55772277/ccb65521-8f95-4365-b577-1c24fd8a5b74)

**Comment by yaobiao131** [comment]
查看安装目录是否存在ffmpeg目录是否存在ffmpeg.exe文件

**Comment by 897601689** [comment]
1.0.1也出现过 暂停重新开始就好了

**Comment by th10010** [comment]
搞定了，谢谢！！
