### ISSUE TITLE
从个人主页进入我的关注列表会闪退

### ISSUE THREAD

**Issue by th10010** [yaobiao131/downkyicore#8]
如图，从我的主页进去，查看我的关注，首次加载列表会为空白，并且切换至全部关注时会卡死、闪退
![11](https://github.com/yaobiao131/downkyicore/assets/55772277/d0d79af0-3ba7-482f-b854-0894aa6c90c6)
![22](https://github.com/yaobiao131/downkyicore/assets/55772277/d35103e3-82fd-4c58-9be5-3585b9d19050)

**Comment by yaobiao131** [comment]
首次空白是已知的，然后闪退我这边不好复现，可能我关注比较少，我这边是没问题的

**Comment by th10010** [comment]
测试了下，确实是只有切换到关注量大的栏目才闪退，20多个的小栏目不闪退

**Comment by yaobiao131** [comment]
好的，我会测试下

**Comment by 1983sxj** [comment]
> 好的，我会测试下

我2000+关注，试了一下全部关注一栏没有BUG。。。

**Comment by 1983sxj** [comment]
> > 好的，我会测试下
> 
> 我2000+关注，试了一下全部关注一栏有时没有BUG。。。有时闪退

刚刚又试了几次，又不闪退了。。。奇了怪了

**Comment by yaobiao131** [comment]
> > > 好的，我会测试下
> > 
> > 
> > 我2000+关注，试了一下全部关注一栏有时没有BUG。。。有时闪退
> 
> 刚刚又试了几次，又不闪退了。。。奇了怪了

我这边也没出过问题、但是优化了一下。下个版本可以再试下
