### ISSUE TITLE
朋友的macbook安装后运行，直接弹窗，寻求解决办法

### ISSUE THREAD

**Issue by th10010** [yaobiao131/downkyicore#81]
如图，朋友的macbook pro m3芯片，安装软件后，运行就会弹出这个错误，请求解决方案，十分感谢。
<img width="345" alt="微信图片_20240422155205" src="https://github.com/yaobiao131/downkyicore/assets/55772277/0a418af1-26b5-4a51-9fc6-2e7dce0af43e">
![20240422154327](https://github.com/yaobiao131/downkyicore/assets/55772277/a45bb1ce-89a9-48f9-a3e7-46453a616853)

**Comment by yaobiao131** [comment]
麻烦发一下显示详细信息里面的内容

**Comment by th10010** [comment]
![Uploading 微信截图_20240422155536.png…]()

**Comment by th10010** [comment]
![31313114](https://github.com/yaobiao131/downkyicore/assets/55772277/df3b6507-93e9-4ddd-bf72-e5ab16dce565)

**Comment by yaobiao131** [comment]
你需要下载arm64版本而不是x86版本

**Comment by th10010** [comment]
arm64也报错的

![414147](https://github.com/yaobiao131/downkyicore/assets/55772277/b7fce22f-fd13-4d9f-bfab-8991f1ebff92)

> 你需要下载arm64版本而不是x86版本

**Comment by yaobiao131** [comment]
由于目前网络上基本没有m3真机测试，暂时不好排查

**Comment by need-it-github** [comment]
实测M1 Ok

**Comment by hu942671090** [comment]
inter版本测试没问题
