### ISSUE TITLE
暂时不可下载杜比视界的视频

### ISSUE THREAD

**Issue by Svie1** [yaobiao131/downkyicore#87]
尝试下载杜比视界的视频  点击解析是没问题的  点击下载选中项会直接闪退(Mac端)

**Comment by Svie1** [comment]
视频地址：https://www.bilibili.com/video/BV1DC4y1f75q/￼
系统版本：macOS Sonoma 14.4.1
所使用的app发行版是OS X arm64  1.0.9
现在有一个新的问题  就是在第一次下载完上述视频的4k版本(因为第一次仅解析识别到了4k版本 在下载完成后才能识别到杜比视界)  选项换到杜比视界后就不可下载了  app会直接闪退  闪退后再对其他视频(即便是无HDR或是杜比视界的视频)进行下载  app都会直接闪退  覆盖安装不可解决此问题

**Comment by yaobiao131** [comment]
我这边测试多次是正常的

**Comment by Svie1** [comment]
好的  我再试下吧

**Comment by Svie1** [comment]
> 我这边测试多次是正常的

今天试了下还是不行啊  重装也不可以解决问题  解析视频是没问题的  只要一下载百分百闪退  无论什么视频
<img width="628" alt="截屏2024-05-06 19 43 47" src="https://github.com/yaobiao131/downkyicore/assets/107756369/26e85e3c-5577-4aa6-9ffd-9a9047144f77">

**Comment by yaobiao131** [comment]
设置中关闭重复视频自动重命名呢

**Comment by Svie1** [comment]
> 设置中关闭重复视频自动重命名呢

OK  解决了
