### ISSUE TITLE
Hi-Res无法混流

### ISSUE THREAD

**Issue by 1983sxj** [yaobiao131/downkyicore#9]
解析下载响应都超级快，但是只要是Hi-Res就无法混流，试了好多个视频，改成非Hi-Res就可以混流。。。
其他非Hi-Res视频都没有这个BUG

**Comment by yaobiao131** [comment]
麻烦给一个测试链接呢

**Comment by 1983sxj** [comment]
> 麻烦给一个测试链接呢

补充两点，暂停下载也没用，ffmpeg替换了也没用
https://www.bilibili.com/video/BV1ky4y1Z7bx/
还有
BV1Yb4y137BN
共同点是Hi-Res

**Comment by yaobiao131** [comment]
> > 麻烦给一个测试链接呢
> 
> 补充两点，暂停下载也没用，ffmpeg替换了也没用 https://www.bilibili.com/video/BV1ky4y1Z7bx/ 还有 BV1Yb4y137BN 共同点是Hi-Res

我这边macOS测试是没有问题的，怀疑是ffmpeg的问题，你那边是windows吗

**Comment by yaobiao131** [comment]
我在windows测试也没问题🤔️

**Comment by 1983sxj** [comment]
> 我在windows测试也没问题🤔️

是windows，可是我试了下哔哩下载姬downkyi1.6.1是好的。。。就是1.6.1解析实在是随缘。。。

**Comment by 1983sxj** [comment]
> > > 麻烦给一个测试链接呢
> > 
> > 
> > 补充两点，暂停下载也没用，ffmpeg替换了也没用 https://www.bilibili.com/video/BV1ky4y1Z7bx/ 还有 BV1Yb4y137BN 共同点是Hi-Res
> 
> 我这边macOS测试是没有问题的，怀疑是ffmpeg的问题，你那边是windows吗

我换了两个ffmpeg还是有问题，我都吐了

**Comment by yaobiao131** [comment]
> > > > 麻烦给一个测试链接呢
> > > 
> > > 
> > > 补充两点，暂停下载也没用，ffmpeg替换了也没用 https://www.bilibili.com/video/BV1ky4y1Z7bx/ 还有 BV1Yb4y137BN 共同点是Hi-Res
> > 
> > 
> > 我这边macOS测试是没有问题的，怀疑是ffmpeg的问题，你那边是windows吗
> 
> 我换了两个ffmpeg还是有问题，我都吐了

下个版本我会加上ffmpeg日志，到时候可以把日志发出来我排查下

**Comment by 1983sxj** [comment]
> > > > > 麻烦给一个测试链接呢
> > > > 
> > > > 
> > > > 补充两点，暂停下载也没用，ffmpeg替换了也没用 https://www.bilibili.com/video/BV1ky4y1Z7bx/ 还有 BV1Yb4y137BN 共同点是Hi-Res
> > > 
> > > 
> > > 我这边macOS测试是没有问题的，怀疑是ffmpeg的问题，你那边是windows吗
> > 
> > 
> > 我换了两个ffmpeg还是有问题，我都吐了
> 
> 下个版本我会加上ffmpeg日志，到时候可以把日志发出来我排查下

好的感谢大佬

**Comment by lhyhopex** [comment]
我这边是如果只下载音频的话无论选哪个音质都会卡在视频混流中那里，反倒是同时下载音频视频的时候可以正常得到mp4，win和macos都是这个结果

**Comment by yaobiao131** [comment]
> 我这边是如果只下载音频的话无论选哪个音质都会卡在视频混流中那里，反倒是同时下载音频视频的时候可以正常得到mp4，win和macos都是这个结果

已修复，晚些会发布

**Comment by yaobiao131** [comment]
> > > > > > 麻烦给一个测试链接呢
> > > > > 
> > > > > 
> > > > > 补充两点，暂停下载也没用，ffmpeg替换了也没用 https://www.bilibili.com/video/BV1ky4y1Z7bx/ 还有 BV1Yb4y137BN 共同点是Hi-Res
> > > > 
> > > > 
> > > > 我这边macOS测试是没有问题的，怀疑是ffmpeg的问题，你那边是windows吗
> > > 
> > > 
> > > 我换了两个ffmpeg还是有问题，我都吐了
> > 
> > 
> > 下个版本我会加上ffmpeg日志，到时候可以把日志发出来我排查下
> 
> 好的感谢大佬

新版本已发布，可以再试下

**Comment by 1983sxj** [comment]
> > > > > > > 麻烦给一个测试链接呢
> > > > > > 
> > > > > > 
> > > > > > 补充两点，暂停下载也没用，ffmpeg替换了也没用 https://www.bilibili.com/video/BV1ky4y1Z7bx/ 还有 BV1Yb4y137BN 共同点是Hi-Res
> > > > > 
> > > > > 
> > > > > 我这边macOS测试是没有问题的，怀疑是ffmpeg的问题，你那边是windows吗
> > > > 
> > > > 
> > > > 我换了两个ffmpeg还是有问题，我都吐了
> > > 
> > > 
> > > 下个版本我会加上ffmpeg日志，到时候可以把日志发出来我排查下
> > 
> > 
> > 好的感谢大佬
> 
> 新版本已发布，可以再试下

好不容易登上来了，确实可以混流了，看了ffmpeg日志也没报错，在我这目前用下来没任何BUG了
