### ISSUE TITLE
vs2022不能成功编译，报错。

### ISSUE THREAD

**Issue by fandebiao** [yaobiao131/downkyicore#93]
工程：Downkyi.Core，无法加载，报错。

![image](https://github.com/yaobiao131/downkyicore/assets/39857470/e00c648d-f3b7-4b57-842e-f2981a46b7d7)

错误信息：

![image](https://github.com/yaobiao131/downkyicore/assets/39857470/6be62a94-1aaa-4a35-b11a-e211bc7d268f)

**Comment by yaobiao131** [comment]
vs编译暂时有点问题，使用jetbrian Rider可以成功编译

**Comment by fandebiao** [comment]
> vs编译暂时有点问题，使用jetbrian Rider可以成功编译

多谢，rider打开没问题。
