### ISSUE TITLE
在检查更新时，程序为最新正式版仍提示"请前往主页下载最新版"

### ISSUE THREAD

**Issue by 3cxc** [yaobiao131/downkyicore#98]
如上，在程序为最新正式版时，检查更新仍提示前往主页下载最新版
![1](https://github.com/yaobiao131/downkyicore/assets/81449257/fa68fa0f-9f9c-46c9-828d-580e8804f6a9)

**Comment by yaobiao131** [comment]
检查更新其实并没有做，跨平台多架构更新比较麻烦，后面有空会做

**Comment by QQ804218** [comment]
> 检查更新其实并没有做，跨平台多架构更新比较麻烦，后面有空会做

可以给个仓库地址也好啊,地址都不给,怎么下载啊...
